#!/bin/sh

# wall=$(find ~/pix/Anime/Wallpaper-anime-66.png)
# wall=$(find ~/pix/Anime/midnight-island.jpeg)
# wall=$(find ~/pix/Anime/space-1600x900.png)
# wall=$(find ~/pix/Anime/Wallpaper-anime-77.jpg)
# wall=$(find ~/pix/carlos/3w6rm6zrogyc1.jpeg)
# wall=$(find ~/pix/Anime/digital-art-boy.jpg)
wall=$(find ~/pix/wallmain/pexels-cesar-perez-733745.jpg)

xwallpaper --zoom $wall

# generate color scheme
wal -c
wal -i $wall

# Refresh the status bar
xdotool key super+F5

