#!/bin/sh
wall=$(find ~/pix/carlos/ -type f -name "*.jpeg" -o -name "*.jpg" -o -name "*.png" | shuf -n 1)
# add this as background wallpaper
xwallpaper --zoom $wall

# generate color scheme
wal -c

wal -i $wall
wal -i $wall
xdotool key super+F5
xdotool key super+F5
