#!/bin/sh

wall=$(find ~/pix/Anime/green-mask.jpg)
xwallpaper --zoom $wall

# this will add my colors from json file
color=$(find ~/.local/bin/pywal/dist/green-mine.json)

# generate color scheme
wal -c
wal --theme $color

# Refresh the status bar
xdotool key super+F5

