#!/bin/sh

# wall=$(find ~/pix/Anime/green-skull.jpg)
wall=$(find ~/pix/Anime/green-mask.jpg)
xwallpaper --zoom $wall

# generate color scheme
wal -c
wal -i $wall --saturate 1

# Refresh the status bar
xdotool key super+F5

