#!/bin/sh

wall=$(find ~/pix/Anime/space-1600x900.png)
 #wall=$(find ~/pix/Anime/pink-japanese-1600x900.png)
# wall=$(find ~/pix/Anime/digital-art-boy.jpg)
xwallpaper --zoom $wall

# generate color scheme
wal -c
wal -i $wall

# Refresh the status bar
xdotool key super+F5

