#!/bin/bash
# this is for Dvorak
xmodmap -e "keycode 66 = Mode_switch"

# alt_R is Caps_Lock
xmodmap -e "keycode 108 = Caps_Lock"

# Set Space as a dual-purpose key (regular space + Mode_switch)
xmodmap -e "keycode 65 = space Mode_switch"

# Map hjkl + Mode_switch to arrow keys
xmodmap -e "keysym h = h H Left"
xmodmap -e "keysym j = j J Down"
xmodmap -e "keysym k = k K Up"
xmodmap -e "keysym l = l L Right"

# Map dhtn + Mode_switch to arrow keys
#xmodmap -e "keysym d = d D Left"
#xmodmap -e "keysym h = h H Down"
#xmodmap -e "keysym t = t T Up"
#xmodmap -e "keysym n = n N Right"

# Map additional keys with Mode_switch
xmodmap -e "keysym u = u U BackSpace"    # Mode_key + f -> Backspace

## Map additional keys with Escape, Return
xmodmap -e "keysym b = b B Return"       # Mode_key + n -> Return/Enter
xmodmap -e "keysym o = o O Delete"       # Mode_key + o -> Escape
xmodmap -e "keysym p = p P Tab"          # Mode_key + r -> Tab
xmodmap -e "keysym e = e E Escape"          # Mode_key + r -> Tab

xmodmap -e "keysym f = f F bracketleft"  # Mode_key + g -> bracketleft
xmodmap -e "keysym g = g G bracketright" # Mode_key + c -> bracketright

xmodmap -e "keysym i = i I parenleft"    # Mode_key + w -> parenleft
xmodmap -e "keysym d = d D parenright"   # Mode_key + e -> parenright
xmodmap -e "keysym c = c C braceleft"    # Mode_key + r -> braceright
xmodmap -e "keysym r = r R braceright"   # Mode_key + l -> braceleft
